version: 2.1

orbs: 
  go: circleci/go@1.7.2

jobs:
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - go/test:
          covermode: atomic
          failfast: true
          race: true

workflows:
  test-workflow:
    jobs:
      - test
